### ISSUE TITLE
what about extension fields?

### ISSUE THREAD

**Issue by alanwilter** [funkwerk/compose_format#14]
See https://docs.docker.com/compose/compose-file/#extension-fields

Mine does not work with `compose_format`:
```yaml
version: '3.8'
x-common: &common
   env_file:
   - public.env
services:
   app:
      <<: *common
      environment:
      - APP_ENV=test
      build:
         context: .
...
```
